FROM node:14 As Production

ENV NODE_ENV=production

WORKDIR /user/src/api

COPY package.json .
COPY yarn.lock .


RUN yarn install
RUN yarn global add typescript
COPY . .

RUN yarn build
COPY .env ./dist/
COPY wait-for-it.sh ./dist/ 
WORKDIR ./dist


# CMD ["./wait-for-it.sh", "postgres:5432", "--", "node",  "src/index.js"]
CMD node src/index.js
